future: true
permalink: /:title/
url: http://skyatlantis.github.io
name: ren_sky
author: ren_sky
qq: 
email: sky_atlantis@sina.com.cn
duoshuo: ren_sky
beian: 
cnzz: 
weibo: ren_sky
github: skyatlantis
paginate: 20
highlighter: rouge
truncate: true
about: "ren_sky"
